forklift_controllers:
  # Publish all joint states
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 1000

  # Wheel torch controllers
  chassis_controller:
    type: effort_controllers/JointGroupEffortController
    joints:
      - front_left_left_rotate_joint
      - front_left_right_rotate_joint
      - front_right_left_rotate_joint
      - front_right_right_rotate_joint
      - back_left_left_rotate_joint
      - back_left_right_rotate_joint
      - back_right_left_rotate_joint
      - back_right_right_rotate_joint

  # Position Controller: Just use as ENCODERS!!
  zero_controller:
    type: effort_controllers/JointGroupEffortController
    joints:
      - front_left_whole_rotate_joint
      - front_right_whole_rotate_joint
      - back_left_whole_rotate_joint
      - back_right_whole_rotate_joint

  fork_controller:
    type: position_controllers/JointPositionController
    joint: beam_fork_slide_joint

  # TODO: the controller of the fork
